// Faculty tidak punya kode, hanya nama
export const mockFaculties = [
  { name: 'Fakultas Ekonomi dan Bisnis' },
  { name: 'Fakultas Hukum' },
  { name: 'Fakultas Teknik' },
  { name: 'Fakultas Psikologi' },
  { name: 'Fakultas Ilmu Komunikasi' },
  { name: 'Fakultas Kedokteran' },
  { name: 'Fakultas Seni Rupa dan Desain' },
  { name: 'Fakultas Teknologi Informasi' },
];

// Key menggunakan nama fakultas, value adalah array program studi dengan kode 3 digit
export const mockMajors = {
  'Fakultas Ekonomi dan Bisnis': [
    { code: '115', name: 'Manajemen' },
    { code: '125', name: 'Akuntansi' },
  ],
  'Fakultas Hukum': [
    { code: '205', name: 'Hukum' },
  ],
  'Fakultas Teknik': [
    { code: '325', name: 'Teknik Sipil' },
    { code: '515', name: 'Teknik Mesin' },
    { code: '315', name: 'Arsitektur' },
    { code: '345', name: 'Perencanaan Wilayah & Tata Kota' },
    { code: '525', name: 'Teknik Elektro' },
    { code: '545', name: 'Teknik Industri' },
  ],
  'Fakultas Psikologi': [
    { code: '705', name: 'Psikologi' },
  ],
  'Fakultas Ilmu Komunikasi': [
    { code: '915', name: 'Ilmu Komunikasi' },
  ],
  'Fakultas Kedokteran': [
    { code: '405', name: 'Kedokteran' },
  ],
  'Fakultas Seni Rupa dan Desain': [
    { code: '625', name: 'Desain Komunikasi Visual' },
    { code: '615', name: 'Desain Interior' },
  ],
  'Fakultas Teknologi Informasi': [
    { code: '535', name: 'Teknik Informatika' },
    { code: '825', name: 'Sistem Informasi' },
  ],
};

export const mockVendors = [
  {
    id: 1,
    name: "Bu Tati's Warung",
    description: "Warung nasi dan lauk pauk tradisional",
    image: '/images/vendors/bu-tati.jpg',
  },
  {
    id: 2,
    name: "Bang Budi Corner",
    description: "Aneka mie instan dan gorengan",
    image: '/images/vendors/bang-budi.jpg',
  },
  {
    id: 3,
    name: "Sakura Bento",
    description: "Japanese bento dan onigiri",
    image: '/images/vendors/sakura.jpg',
  },
  {
    id: 4,
    name: "Kopi Kenangan",
    description: "Kopi dan minuman segar",
    image: '/images/vendors/kopi.jpg',
  },
];

export const mockMenus = [
  {
    id: 1,
    vendorId: 2,
    vendorName: "Bang Budi Corner",
    name: "Indomie Goreng Spesial",
    category: "Instant Noodles",
    price: 12000,
    image: "/images/menus/indomie-goreng.jpg",
    estimatedTime: "5-10 menit",
    description: "Indomie goreng dengan telur, sayuran, dan bumbu spesial",
    stock: 50,
    additionals: [
      { name: "Telur 1", price: 3000 },
      { name: "Telur 2", price: 5000 },
      { name: "Kornet", price: 5000 },
      { name: "Keju", price: 4000 },
    ],
  },
  {
    id: 2,
    vendorId: 2,
    vendorName: "Bang Budi Corner",
    name: "Indomie Rica-Rica",
    category: "Instant Noodles",
    price: 13000,
    image: "/images/sambal_rica.png",
    estimatedTime: "5-10 menit",
    description: "Indomie dengan sambal rica-rica pedas dan gurih",
    stock: 45,
    additionals: [
      { name: "Telur 1", price: 3000 },
      { name: "Telur 2", price: 5000 },
      { name: "Kornet", price: 5000 },
      { name: "Keju", price: 4000 },
    ],
  },
  {
    id: 10,
    vendorId: 2,
    vendorName: "Bang Budi Corner",
    name: "Mie Goreng",
    category: "Instant Noodles",
    price: 10000,
    image: "/images/sakura_migoreng.png",
    estimatedTime: "5-10 menit",
    description: "Mie goreng dengan sayuran segar",
    stock: 45,
    additionals: [
      { name: "Telur 1", price: 3000 },
      { name: "Bakso 3pcs", price: 6000 },
    ],
  },
  {
    id: 3,
    vendorId: 2,
    vendorName: "Bang Budi Corner",
    name: "Gorengan Mix",
    category: "Fritters / Snacks",
    price: 8000,
    image: "/images/menus/gorengan.jpg",
    estimatedTime: "5-10 menit",
    description: "Gorengan campur (tahu, tempe, pisang, bakwan)",
    stock: 30,
    additionals: [],
  },
  {
    id: 4,
    vendorId: 3,
    vendorName: "Sakura Bento",
    name: "Chicken Teriyaki Bento",
    category: "Bento / Rice",
    price: 25000,
    image: "/images/menus/chicken-teriyaki.jpg",
    estimatedTime: "10-15 menit",
    description: "Nasi dengan ayam teriyaki, sayuran, dan telur",
    stock: 20,
    additionals: [
      { name: "Extra Chicken", price: 10000 },
      { name: "Miso Soup", price: 5000 },
    ],
  },
  {
    id: 5,
    vendorId: 3,
    vendorName: "Sakura Bento",
    name: "Onigiri Salmon",
    category: "Bento / Rice",
    price: 15000,
    image: "/images/menus/onigiri.jpg",
    estimatedTime: "5-10 menit",
    description: "Nasi kepal dengan isian salmon",
    stock: 25,
    additionals: [],
  },
  {
    id: 6,
    vendorId: 1,
    vendorName: "Bu Tati's Warung",
    name: "Nasi Goreng Kampung",
    category: "Bento / Rice",
    price: 18000,
    image: "/images/menus/nasi-goreng.jpg",
    estimatedTime: "10-15 menit",
    description: "Nasi goreng dengan ayam, telur, dan kerupuk",
    stock: 35,
    additionals: [
      { name: "Telur Mata Sapi", price: 4000 },
      { name: "Ayam Goreng", price: 8000 },
    ],
  },
  {
    id: 7,
    vendorId: 1,
    vendorName: "Bu Tati's Warung",
    name: "Soto Ayam",
    category: "Soup",
    price: 15000,
    image: "/images/menus/soto-ayam.jpg",
    estimatedTime: "10-15 menit",
    description: "Soto ayam kuning dengan nasi dan kerupuk",
    stock: 40,
    additionals: [
      { name: "Nasi Extra", price: 3000 },
      { name: "Perkedel", price: 3000 },
    ],
  },
  {
    id: 8,
    vendorId: 4,
    vendorName: "Kopi Kenangan",
    name: "Es Kopi Susu",
    category: "Beverages",
    price: 12000,
    image: "/images/menus/es-kopi.jpg",
    estimatedTime: "5-10 menit",
    description: "Kopi susu dingin yang segar",
    stock: 100,
    additionals: [
      { name: "Extra Shot", price: 5000 },
      { name: "Brown Sugar", price: 3000 },
    ],
  },
  {
    id: 9,
    vendorId: 4,
    vendorName: "Kopi Kenangan",
    name: "Thai Tea",
    category: "Beverages",
    price: 10000,
    image: "/images/menus/thai-tea.jpg",
    estimatedTime: "5-10 menit",
    description: "Thai tea original dengan susu",
    stock: 80,
    additionals: [
      { name: "Extra Jelly", price: 3000 },
    ],
  },
];

export const mockOrders = [
  {
    id: 1,
    userId: "82525002",
    userName: "John Doe",
    vendorId: 2,
    vendorName: "Bang Budi Corner",
    items: [
      {
        menuId: 1,
        menuName: "Indomie Goreng Spesial",
        quantity: 2,
        price: 12000,
        additionals: [
          { name: "Telur 1", price: 3000 },
        ],
      },
    ],
    totalPrice: 30000,
    status: "Processing",
    pickupLocation: "Stand B2",
    orderDate: "2025-10-27T08:30:00Z",
  },
  {
    id: 2,
    userId: "82525002",
    userName: "John Doe",
    vendorId: 3,
    vendorName: "Sakura Bento",
    items: [
      {
        menuId: 4,
        menuName: "Chicken Teriyaki Bento",
        quantity: 1,
        price: 25000,
        additionals: [],
      },
    ],
    totalPrice: 25000,
    status: "Done",
    pickupLocation: "Stand C1",
    orderDate: "2025-10-26T12:15:00Z",
  },
];

export const mockCategories = [
  "Instant Noodles",
  "Fritters / Snacks",
  "Bento / Rice",
  "Soup",
  "Beverages",
];